//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemicalWarehouseWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChemicalWarehouseDBEntities3 : DbContext
    {
        public ChemicalWarehouseDBEntities3()
            : base("name=ChemicalWarehouseDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Departments> Departments { get; set; }
        public DbSet<HazardClasses> HazardClasses { get; set; }
        public DbSet<ReagentBatches> ReagentBatches { get; set; }
        public DbSet<Reagents> Reagents { get; set; }
        public DbSet<ReagentTypes> ReagentTypes { get; set; }
        public DbSet<StorageLocations> StorageLocations { get; set; }
        public DbSet<Suppliers> Suppliers { get; set; }
        public DbSet<UnitsOfMeasure> UnitsOfMeasure { get; set; }
        public DbSet<UserRoles> UserRoles { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<WarehouseOperations> WarehouseOperations { get; set; }
        public DbSet<WarehouseZones> WarehouseZones { get; set; }
    }
}
